#!/usr/bin/env python3
"""Regenerates ui/internal/probes.slint.

The probe strings are literals in a checked-in source file rather than something build.rs
writes, because a consuming crate re-parses this crate's .slint sources with its own compiler
configuration and cannot import anything generated into OUT_DIR.
"""

import pathlib

# See the header written into the generated file for why these are this large.
CHARS = 4096
LINES = 512

chars = "".join("0123456789"[i % 10] for i in range(CHARS))
lines = "\\n".join(["x"] * LINES)

out = f'''// GENERATED FILE. Regenerate with tools/gen-probes.py; do not hand-edit the literals.
//
// Measuring sticks for GridMetrics.
//
// They are absurdly long on purpose. Slint rounds a Text element's reported width up to a
// whole pixel, so measuring a few characters gives a badly wrong advance: a single character
// of a 7.83px font reports 8px, and that 2.2% error accumulates into more than a full
// character of drift by column 45. The rounding adds at most one pixel in total however long
// the string is, so dividing a long probe by its length makes the error vanish. At {CHARS}
// characters it is 0.00024px per column, or 0.06px across a 240 column line.
//
// They are literals in a checked-in file rather than generated by build.rs because a
// consuming crate re-parses these sources and cannot see anything under OUT_DIR.
export global Probes {{
    out property <string> chars: "{chars}";
    out property <int> char-count: {CHARS};
    out property <string> lines: "{lines}";
    out property <int> line-count: {LINES};
}}
'''

target = pathlib.Path(__file__).resolve().parent.parent / "ui/internal/probes.slint"
target.write_text(out)
print(f"wrote {target} ({len(out)} bytes)")
